/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { AvatarSize } from "./components/sux-avatar/interfaces";
import { BodyClassification, BodySize } from "./components/sux-body/interfaces";
import { ButtonSize, ButtonVariant } from "./components/sux-button/interfaces";
import { CodeSize } from "./components/sux-code/interfaces";
import { DetailClassification, DetailSize, DetailWeight } from "./components/sux-detail/interfaces";
import { FieldLabelPosition, FieldLabelSize } from "./components/sux-field-label/interfaces";
import { HeadingClassification, HeadingSize, HeadingWeight } from "./components/sux-heading/interfaces";
import { HelpTextSize, HelpTextVariant } from "./components/sux-help-text/interfaces";
import { IconButtonShape, IconButtonSize, IconButtonVariant } from "./components/sux-icon-button/interface";
import { IconLibraryMutator, IconLibraryResolver } from "./components/sux-icon-library/icon-library-registry";
import { LinkSize, LinkVariant } from "./components/sux-link/interface";
import { LabelPosition } from "./components/sux-picker/interfaces";
import { RadioSize } from "./components/sux-radio/interfaces";
import { TagSize, TagStatus, TagVariant } from "./components/sux-tag/interfaces";
import { TextAreaSize } from "./components/sux-text-area/innterfaces";
import { TextFieldSize, TextFieldType } from "./components/sux-text-field/interfaces";
export namespace Components {
    interface SuxActionable {
        /**
          * href attribute to handle link
         */
        "href"?: string;
        /**
          * role attribute to define the function
         */
        "role"?: string;
        /**
          * target attribute for the link
         */
        "target": '_blank' | '_parent' | '_self' | '_top';
    }
    interface SuxAvatar {
        /**
          * The image url for the image to be displayed on the Avatar
         */
        "imageUrl": string;
        /**
          * optionally pass initials to display on the Avatar
         */
        "initials": string;
        /**
          * pass an image alt text for accessibility
         */
        "label": string;
        /**
          * specify the size of the Avatar, defaults to xxxl
         */
        "size": AvatarSize;
    }
    interface SuxBody {
        /**
          * Classification
         */
        "classification": BodyClassification;
        /**
          * Size
         */
        "size": BodySize;
    }
    interface SuxButton {
        /**
          * is the button disabled
         */
        "disabled"?: boolean;
        /**
          * optionally pass an icon to display at the end of a button - accepts ui icon names
         */
        "iconEnd"?: boolean;
        /**
          * optionally pass an icon to display at the start of a button - accepts ui icon names
         */
        "iconStart"?: boolean;
        /**
          * optionally add a sux-loader component to the button, disabling interaction.
         */
        "isLoading"?: boolean;
        /**
          * Applies to the aria-label attribute on the button or hyperlink
         */
        "label": string;
        /**
          * The name attribute to apply to the button
         */
        "name"?: string;
        /**
          * Is quiet makes the button appear with least prominence.
         */
        "quiet": boolean;
        /**
          * specify the size of the button, defaults to m
         */
        "size": ButtonSize;
        /**
          * The type attribute to apply to the button
         */
        "type"?: string;
        /**
          * specify the appearance style of the button, defaults to solid.
         */
        "variant": ButtonVariant;
    }
    interface SuxCheckbox {
        /**
          * Checked value of checkbox
         */
        "checked": boolean;
        /**
          * disable the checkbox
         */
        "disabled": boolean;
        /**
          * Error
         */
        "error": boolean;
        /**
          * Help text
         */
        "helpText": string;
        /**
          * Indeterminate state of checkbox
         */
        "indeterminate": boolean;
        /**
          * Label for the checkbox
         */
        "label": string;
        /**
          * The checkbox name
         */
        "name": string;
        /**
          * Read only
         */
        "readonly": boolean;
        /**
          * Value
         */
        "value": string;
    }
    interface SuxCode {
        /**
          * Size
         */
        "size": CodeSize;
    }
    interface SuxDetail {
        /**
          * Classification
         */
        "classification": DetailClassification;
        /**
          * Size
         */
        "size": DetailSize;
        /**
          * Weight
         */
        "weight": DetailWeight;
    }
    interface SuxFieldLabel {
        /**
          * Disabled
         */
        "disabled": boolean;
        /**
          * Label
         */
        "label": string;
        /**
          * position
         */
        "position": FieldLabelPosition;
        /**
          * Required
         */
        "required": boolean;
        /**
          * Size
         */
        "size": FieldLabelSize;
    }
    interface SuxHeading {
        /**
          * Heading classification
         */
        "classification": HeadingClassification;
        /**
          * Heading  size
         */
        "size": HeadingSize;
        /**
          * Overwrite Tag
         */
        "tag"?: string;
        /**
          * Heading weight
         */
        "weight": HeadingWeight;
    }
    interface SuxHelpText {
        /**
          * disabled
         */
        "disabled": boolean;
        /**
          * Icon
         */
        "icon": boolean;
        /**
          * size
         */
        "size": HelpTextSize;
        /**
          * text
         */
        "text": string;
        /**
          * Variant
         */
        "variant": HelpTextVariant;
    }
    interface SuxIcon {
        /**
          * An alternative description to use for accessibility. If omitted, the name or src will be used to generate it.
         */
        "label": string;
        /**
          * The name of a registered custom icon library.
         */
        "library": string;
        /**
          * The name of the icon to draw.
         */
        "name": string;
        "redraw": () => Promise<void>;
        /**
          * An external URL of an SVG file.
         */
        "src": string;
    }
    interface SuxIconButton {
        /**
          * is the button disabled
         */
        "disabled"?: boolean;
        /**
          * When set, the underlying button will be rendered as an <a> with this href instead of a <button>
         */
        "href": string;
        /**
          * A description that gets read by screen readers and other assistive devices. For optimal accessibility, you should always include a label that describes what the icon button does.
         */
        "label": string;
        /**
          * The Name of Registered Icon in the Library
         */
        "library": string;
        /**
          * Name of The Icon
         */
        "name": string;
        /**
          * Is quiet makes the button appear with least prominence.
         */
        "quiet": boolean;
        /**
          * specify the style of the icon button, defaults to default.
         */
        "shape": IconButtonShape;
        /**
          * specify the size of the icon button, defaults to m
         */
        "size": IconButtonSize;
        /**
          * Optionally provide external url for custom SVG icon
         */
        "src": string;
        /**
          * When set, defines the target of the link
         */
        "target": '_blank' | '_parent' | '_self' | '_top';
        /**
          * specify the variant of the icon button, defaults to primary.
         */
        "variant": IconButtonVariant;
    }
    interface SuxIconLibrary {
        /**
          * A function that mutates the SVG element before it renders.
         */
        "mutator": IconLibraryMutator;
        /**
          * The name of the icon library.
         */
        "name": string;
        /**
          * A function that translates an icon name to a URL where the corresponding SVG file exists The URL can be local or a CORS-enabled endpoint.
         */
        "resolver": IconLibraryResolver;
    }
    interface SuxLink {
        "disabled": boolean;
        "href": string;
        /**
          * specify the size of the Link, defaults to m
         */
        "size": LinkSize;
        /**
          * specify the appearance of the Link, defaults to primary.
         */
        "variant": LinkVariant;
    }
    interface SuxMenuItem {
        /**
          * active
         */
        "active": boolean;
        /**
          * disabled
         */
        "disabled": boolean;
        /**
          * no wrap
         */
        "noWrap": boolean;
        /**
          * selected
         */
        "selected": boolean;
        /**
          * value
         */
        "value": string;
    }
    interface SuxPicker {
        /**
          * Disabled
         */
        "disabled": boolean;
        /**
          * Error
         */
        "error": boolean;
        /**
          * Help Text
         */
        "helpText": string;
        /**
          * label
         */
        "label": string;
        /**
          * Label position
         */
        "labelPosition": LabelPosition;
        /**
          * Placeholder
         */
        "placeholder": string;
        /**
          * quiet
         */
        "quiet": boolean;
        /**
          * Read only
         */
        "readonly": boolean;
        /**
          * Required
         */
        "required": boolean;
        /**
          * Value
         */
        "value": string;
        /**
          * Width
         */
        "width": string;
    }
    interface SuxRadio {
        /**
          * Checked state
         */
        "checked": boolean;
        /**
          * disabled state
         */
        "disabled": boolean;
        /**
          * label for the radio button
         */
        "label"?: string;
        /**
          * Name of the radio
         */
        "name": string;
        /**
          * size of the radio button
         */
        "size": RadioSize;
        /**
          * Value of the radio
         */
        "value": string;
    }
    interface SuxRadioGroup {
        /**
          * The validation error text
         */
        "errorText"?: string;
        /**
          * The help or explanation text
         */
        "helpText"?: string;
        /**
          * Presentational only. Renders the Radio Group as invalid.
         */
        "invalid": boolean;
        /**
          * The label of the radio group. For HTML content, use the `label` slot instead.
         */
        "label"?: string;
        /**
          * The name of the radio group - submitted with form data. Must match the name of the radios in the group.
         */
        "name": string;
        /**
          * The value of the current selected radio in the group. Changing this will also mark that radio as checked in the UI.
         */
        "value"?: any | null;
    }
    interface SuxResponsiveMedia {
        /**
          * The aspect ratio of the Responsive media in the format of `width:height`, e.g. `16:9`, `4:3`, or `1:1`. Ratios not in this format will be ignored.
         */
        "aspectRatio": string;
        /**
          * Determines how content will be resized to fit its container.
         */
        "fit": 'contain' | 'cover';
    }
    interface SuxSwitch {
        /**
          * Checked state of the switch
         */
        "checked": boolean;
        /**
          * Disabled state of the switch
         */
        "disabled": boolean;
        /**
          * Label for the switch
         */
        "label": string;
        /**
          * Name of the switch
         */
        "name": string;
        /**
          * Value of the switch
         */
        "value": string;
    }
    interface SuxTag {
        /**
          * Prefix
         */
        "hasPrefix": boolean;
        /**
          * suffix
         */
        "hasSuffix": boolean;
        /**
          * Size
         */
        "size": TagSize;
        /**
          * State
         */
        "status": TagStatus;
        /**
          * Variant
         */
        "variant": TagVariant;
    }
    interface SuxTextArea {
        /**
          * disabled input
         */
        "disabled": boolean;
        /**
          * Error
         */
        "error": boolean;
        /**
          * Error message
         */
        "errorText": string;
        /**
          * Help text
         */
        "helpText": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Label position
         */
        "labelPosition": 'top' | 'side';
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * read only
         */
        "readonly": boolean;
        /**
          * Required
         */
        "required": boolean;
        /**
          * size of the input
         */
        "size": TextAreaSize;
        /**
          * valid icon
         */
        "validIcon": boolean;
        /**
          * value of the input
         */
        "value": string;
        /**
          * width of the input
         */
        "width": string;
    }
    interface SuxTextField {
        /**
          * disabled input
         */
        "disabled": boolean;
        /**
          * Error
         */
        "error": boolean;
        /**
          * Error message
         */
        "errorText": string;
        /**
          * Help text
         */
        "helpText": string;
        /**
          * Label text
         */
        "label": string;
        /**
          * Label position
         */
        "labelPosition": 'top' | 'side';
        /**
          * Placeholder text
         */
        "placeholder": string;
        /**
          * read only
         */
        "readonly": boolean;
        /**
          * Required
         */
        "required": boolean;
        /**
          * size of the input
         */
        "size": TextFieldSize;
        /**
          * Input type
         */
        "type": TextFieldType;
        /**
          * valid icon
         */
        "validIcon": boolean;
        /**
          * value of the input
         */
        "value": string;
        /**
          * width of the input
         */
        "width": string;
    }
}
declare global {
    interface HTMLSuxActionableElement extends Components.SuxActionable, HTMLStencilElement {
    }
    var HTMLSuxActionableElement: {
        prototype: HTMLSuxActionableElement;
        new (): HTMLSuxActionableElement;
    };
    interface HTMLSuxAvatarElement extends Components.SuxAvatar, HTMLStencilElement {
    }
    var HTMLSuxAvatarElement: {
        prototype: HTMLSuxAvatarElement;
        new (): HTMLSuxAvatarElement;
    };
    interface HTMLSuxBodyElement extends Components.SuxBody, HTMLStencilElement {
    }
    var HTMLSuxBodyElement: {
        prototype: HTMLSuxBodyElement;
        new (): HTMLSuxBodyElement;
    };
    interface HTMLSuxButtonElement extends Components.SuxButton, HTMLStencilElement {
    }
    var HTMLSuxButtonElement: {
        prototype: HTMLSuxButtonElement;
        new (): HTMLSuxButtonElement;
    };
    interface HTMLSuxCheckboxElement extends Components.SuxCheckbox, HTMLStencilElement {
    }
    var HTMLSuxCheckboxElement: {
        prototype: HTMLSuxCheckboxElement;
        new (): HTMLSuxCheckboxElement;
    };
    interface HTMLSuxCodeElement extends Components.SuxCode, HTMLStencilElement {
    }
    var HTMLSuxCodeElement: {
        prototype: HTMLSuxCodeElement;
        new (): HTMLSuxCodeElement;
    };
    interface HTMLSuxDetailElement extends Components.SuxDetail, HTMLStencilElement {
    }
    var HTMLSuxDetailElement: {
        prototype: HTMLSuxDetailElement;
        new (): HTMLSuxDetailElement;
    };
    interface HTMLSuxFieldLabelElement extends Components.SuxFieldLabel, HTMLStencilElement {
    }
    var HTMLSuxFieldLabelElement: {
        prototype: HTMLSuxFieldLabelElement;
        new (): HTMLSuxFieldLabelElement;
    };
    interface HTMLSuxHeadingElement extends Components.SuxHeading, HTMLStencilElement {
    }
    var HTMLSuxHeadingElement: {
        prototype: HTMLSuxHeadingElement;
        new (): HTMLSuxHeadingElement;
    };
    interface HTMLSuxHelpTextElement extends Components.SuxHelpText, HTMLStencilElement {
    }
    var HTMLSuxHelpTextElement: {
        prototype: HTMLSuxHelpTextElement;
        new (): HTMLSuxHelpTextElement;
    };
    interface HTMLSuxIconElement extends Components.SuxIcon, HTMLStencilElement {
    }
    var HTMLSuxIconElement: {
        prototype: HTMLSuxIconElement;
        new (): HTMLSuxIconElement;
    };
    interface HTMLSuxIconButtonElement extends Components.SuxIconButton, HTMLStencilElement {
    }
    var HTMLSuxIconButtonElement: {
        prototype: HTMLSuxIconButtonElement;
        new (): HTMLSuxIconButtonElement;
    };
    interface HTMLSuxIconLibraryElement extends Components.SuxIconLibrary, HTMLStencilElement {
    }
    var HTMLSuxIconLibraryElement: {
        prototype: HTMLSuxIconLibraryElement;
        new (): HTMLSuxIconLibraryElement;
    };
    interface HTMLSuxLinkElement extends Components.SuxLink, HTMLStencilElement {
    }
    var HTMLSuxLinkElement: {
        prototype: HTMLSuxLinkElement;
        new (): HTMLSuxLinkElement;
    };
    interface HTMLSuxMenuItemElement extends Components.SuxMenuItem, HTMLStencilElement {
    }
    var HTMLSuxMenuItemElement: {
        prototype: HTMLSuxMenuItemElement;
        new (): HTMLSuxMenuItemElement;
    };
    interface HTMLSuxPickerElement extends Components.SuxPicker, HTMLStencilElement {
    }
    var HTMLSuxPickerElement: {
        prototype: HTMLSuxPickerElement;
        new (): HTMLSuxPickerElement;
    };
    interface HTMLSuxRadioElement extends Components.SuxRadio, HTMLStencilElement {
    }
    var HTMLSuxRadioElement: {
        prototype: HTMLSuxRadioElement;
        new (): HTMLSuxRadioElement;
    };
    interface HTMLSuxRadioGroupElement extends Components.SuxRadioGroup, HTMLStencilElement {
    }
    var HTMLSuxRadioGroupElement: {
        prototype: HTMLSuxRadioGroupElement;
        new (): HTMLSuxRadioGroupElement;
    };
    interface HTMLSuxResponsiveMediaElement extends Components.SuxResponsiveMedia, HTMLStencilElement {
    }
    var HTMLSuxResponsiveMediaElement: {
        prototype: HTMLSuxResponsiveMediaElement;
        new (): HTMLSuxResponsiveMediaElement;
    };
    interface HTMLSuxSwitchElement extends Components.SuxSwitch, HTMLStencilElement {
    }
    var HTMLSuxSwitchElement: {
        prototype: HTMLSuxSwitchElement;
        new (): HTMLSuxSwitchElement;
    };
    interface HTMLSuxTagElement extends Components.SuxTag, HTMLStencilElement {
    }
    var HTMLSuxTagElement: {
        prototype: HTMLSuxTagElement;
        new (): HTMLSuxTagElement;
    };
    interface HTMLSuxTextAreaElement extends Components.SuxTextArea, HTMLStencilElement {
    }
    var HTMLSuxTextAreaElement: {
        prototype: HTMLSuxTextAreaElement;
        new (): HTMLSuxTextAreaElement;
    };
    interface HTMLSuxTextFieldElement extends Components.SuxTextField, HTMLStencilElement {
    }
    var HTMLSuxTextFieldElement: {
        prototype: HTMLSuxTextFieldElement;
        new (): HTMLSuxTextFieldElement;
    };
    interface HTMLElementTagNameMap {
        "sux-actionable": HTMLSuxActionableElement;
        "sux-avatar": HTMLSuxAvatarElement;
        "sux-body": HTMLSuxBodyElement;
        "sux-button": HTMLSuxButtonElement;
        "sux-checkbox": HTMLSuxCheckboxElement;
        "sux-code": HTMLSuxCodeElement;
        "sux-detail": HTMLSuxDetailElement;
        "sux-field-label": HTMLSuxFieldLabelElement;
        "sux-heading": HTMLSuxHeadingElement;
        "sux-help-text": HTMLSuxHelpTextElement;
        "sux-icon": HTMLSuxIconElement;
        "sux-icon-button": HTMLSuxIconButtonElement;
        "sux-icon-library": HTMLSuxIconLibraryElement;
        "sux-link": HTMLSuxLinkElement;
        "sux-menu-item": HTMLSuxMenuItemElement;
        "sux-picker": HTMLSuxPickerElement;
        "sux-radio": HTMLSuxRadioElement;
        "sux-radio-group": HTMLSuxRadioGroupElement;
        "sux-responsive-media": HTMLSuxResponsiveMediaElement;
        "sux-switch": HTMLSuxSwitchElement;
        "sux-tag": HTMLSuxTagElement;
        "sux-text-area": HTMLSuxTextAreaElement;
        "sux-text-field": HTMLSuxTextFieldElement;
    }
}
declare namespace LocalJSX {
    interface SuxActionable {
        /**
          * href attribute to handle link
         */
        "href"?: string;
        /**
          * role attribute to define the function
         */
        "role"?: string;
        /**
          * target attribute for the link
         */
        "target"?: '_blank' | '_parent' | '_self' | '_top';
    }
    interface SuxAvatar {
        /**
          * The image url for the image to be displayed on the Avatar
         */
        "imageUrl"?: string;
        /**
          * optionally pass initials to display on the Avatar
         */
        "initials"?: string;
        /**
          * pass an image alt text for accessibility
         */
        "label"?: string;
        /**
          * specify the size of the Avatar, defaults to xxxl
         */
        "size"?: AvatarSize;
    }
    interface SuxBody {
        /**
          * Classification
         */
        "classification"?: BodyClassification;
        /**
          * Size
         */
        "size"?: BodySize;
    }
    interface SuxButton {
        /**
          * is the button disabled
         */
        "disabled"?: boolean;
        /**
          * optionally pass an icon to display at the end of a button - accepts ui icon names
         */
        "iconEnd"?: boolean;
        /**
          * optionally pass an icon to display at the start of a button - accepts ui icon names
         */
        "iconStart"?: boolean;
        /**
          * optionally add a sux-loader component to the button, disabling interaction.
         */
        "isLoading"?: boolean;
        /**
          * Applies to the aria-label attribute on the button or hyperlink
         */
        "label"?: string;
        /**
          * The name attribute to apply to the button
         */
        "name"?: string;
        /**
          * Is quiet makes the button appear with least prominence.
         */
        "quiet"?: boolean;
        /**
          * specify the size of the button, defaults to m
         */
        "size"?: ButtonSize;
        /**
          * The type attribute to apply to the button
         */
        "type"?: string;
        /**
          * specify the appearance style of the button, defaults to solid.
         */
        "variant"?: ButtonVariant;
    }
    interface SuxCheckbox {
        /**
          * Checked value of checkbox
         */
        "checked"?: boolean;
        /**
          * disable the checkbox
         */
        "disabled"?: boolean;
        /**
          * Error
         */
        "error"?: boolean;
        /**
          * Help text
         */
        "helpText"?: string;
        /**
          * Indeterminate state of checkbox
         */
        "indeterminate"?: boolean;
        /**
          * Label for the checkbox
         */
        "label"?: string;
        /**
          * The checkbox name
         */
        "name"?: string;
        /**
          * Fired when an element has lost focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * Fired when the value of the input changes
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * Fired when an alteration to the input's value is committed by the user
         */
        "onSuxinput"?: (event: CustomEvent<any>) => void;
        /**
          * Read only
         */
        "readonly"?: boolean;
        /**
          * Value
         */
        "value"?: string;
    }
    interface SuxCode {
        /**
          * Size
         */
        "size"?: CodeSize;
    }
    interface SuxDetail {
        /**
          * Classification
         */
        "classification"?: DetailClassification;
        /**
          * Size
         */
        "size"?: DetailSize;
        /**
          * Weight
         */
        "weight"?: DetailWeight;
    }
    interface SuxFieldLabel {
        /**
          * Disabled
         */
        "disabled"?: boolean;
        /**
          * Label
         */
        "label"?: string;
        /**
          * position
         */
        "position"?: FieldLabelPosition;
        /**
          * Required
         */
        "required"?: boolean;
        /**
          * Size
         */
        "size"?: FieldLabelSize;
    }
    interface SuxHeading {
        /**
          * Heading classification
         */
        "classification"?: HeadingClassification;
        /**
          * Heading  size
         */
        "size"?: HeadingSize;
        /**
          * Overwrite Tag
         */
        "tag"?: string;
        /**
          * Heading weight
         */
        "weight"?: HeadingWeight;
    }
    interface SuxHelpText {
        /**
          * disabled
         */
        "disabled"?: boolean;
        /**
          * Icon
         */
        "icon"?: boolean;
        /**
          * size
         */
        "size"?: HelpTextSize;
        /**
          * text
         */
        "text"?: string;
        /**
          * Variant
         */
        "variant"?: HelpTextVariant;
    }
    interface SuxIcon {
        /**
          * An alternative description to use for accessibility. If omitted, the name or src will be used to generate it.
         */
        "label"?: string;
        /**
          * The name of a registered custom icon library.
         */
        "library"?: string;
        /**
          * The name of the icon to draw.
         */
        "name"?: string;
        /**
          * Emitted when the icon failed to load.
         */
        "onSux-error"?: (event: CustomEvent<{ status?: number }>) => void;
        /**
          * Emitted when the icon has loaded.
         */
        "onSux-load"?: (event: CustomEvent<any>) => void;
        /**
          * An external URL of an SVG file.
         */
        "src"?: string;
    }
    interface SuxIconButton {
        /**
          * is the button disabled
         */
        "disabled"?: boolean;
        /**
          * When set, the underlying button will be rendered as an <a> with this href instead of a <button>
         */
        "href"?: string;
        /**
          * A description that gets read by screen readers and other assistive devices. For optimal accessibility, you should always include a label that describes what the icon button does.
         */
        "label"?: string;
        /**
          * The Name of Registered Icon in the Library
         */
        "library"?: string;
        /**
          * Name of The Icon
         */
        "name"?: string;
        /**
          * Is quiet makes the button appear with least prominence.
         */
        "quiet"?: boolean;
        /**
          * specify the style of the icon button, defaults to default.
         */
        "shape"?: IconButtonShape;
        /**
          * specify the size of the icon button, defaults to m
         */
        "size"?: IconButtonSize;
        /**
          * Optionally provide external url for custom SVG icon
         */
        "src"?: string;
        /**
          * When set, defines the target of the link
         */
        "target"?: '_blank' | '_parent' | '_self' | '_top';
        /**
          * specify the variant of the icon button, defaults to primary.
         */
        "variant"?: IconButtonVariant;
    }
    interface SuxIconLibrary {
        /**
          * A function that mutates the SVG element before it renders.
         */
        "mutator"?: IconLibraryMutator;
        /**
          * The name of the icon library.
         */
        "name"?: string;
        /**
          * A function that translates an icon name to a URL where the corresponding SVG file exists The URL can be local or a CORS-enabled endpoint.
         */
        "resolver"?: IconLibraryResolver;
    }
    interface SuxLink {
        "disabled"?: boolean;
        "href"?: string;
        /**
          * specify the size of the Link, defaults to m
         */
        "size"?: LinkSize;
        /**
          * specify the appearance of the Link, defaults to primary.
         */
        "variant"?: LinkVariant;
    }
    interface SuxMenuItem {
        /**
          * active
         */
        "active"?: boolean;
        /**
          * disabled
         */
        "disabled"?: boolean;
        /**
          * no wrap
         */
        "noWrap"?: boolean;
        /**
          * Fires when the element loses focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * Fires when the value of the input changes
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * tabindex
         */
        "onSuxclick"?: (event: CustomEvent<any>) => void;
        /**
          * Fires when an alteration to the input's value is made
         */
        "onSuxinput"?: (event: CustomEvent<any>) => void;
        /**
          * selected
         */
        "selected"?: boolean;
        /**
          * value
         */
        "value"?: string;
    }
    interface SuxPicker {
        /**
          * Disabled
         */
        "disabled"?: boolean;
        /**
          * Error
         */
        "error"?: boolean;
        /**
          * Help Text
         */
        "helpText"?: string;
        /**
          * label
         */
        "label"?: string;
        /**
          * Label position
         */
        "labelPosition"?: LabelPosition;
        /**
          * Placeholder
         */
        "placeholder"?: string;
        /**
          * quiet
         */
        "quiet"?: boolean;
        /**
          * Read only
         */
        "readonly"?: boolean;
        /**
          * Required
         */
        "required"?: boolean;
        /**
          * Value
         */
        "value"?: string;
        /**
          * Width
         */
        "width"?: string;
    }
    interface SuxRadio {
        /**
          * Checked state
         */
        "checked"?: boolean;
        /**
          * disabled state
         */
        "disabled"?: boolean;
        /**
          * label for the radio button
         */
        "label"?: string;
        /**
          * Name of the radio
         */
        "name"?: string;
        /**
          * Fired when an element has lost focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * Fired when an element has lost focus
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * size of the radio button
         */
        "size"?: RadioSize;
        /**
          * Value of the radio
         */
        "value"?: string;
    }
    interface SuxRadioGroup {
        /**
          * The validation error text
         */
        "errorText"?: string;
        /**
          * The help or explanation text
         */
        "helpText"?: string;
        /**
          * Presentational only. Renders the Radio Group as invalid.
         */
        "invalid"?: boolean;
        /**
          * The label of the radio group. For HTML content, use the `label` slot instead.
         */
        "label"?: string;
        /**
          * The name of the radio group - submitted with form data. Must match the name of the radios in the group.
         */
        "name"?: string;
        /**
          * Fired when the value of the input changes - [HTMLElement/input_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event)
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * The value of the current selected radio in the group. Changing this will also mark that radio as checked in the UI.
         */
        "value"?: any | null;
    }
    interface SuxResponsiveMedia {
        /**
          * The aspect ratio of the Responsive media in the format of `width:height`, e.g. `16:9`, `4:3`, or `1:1`. Ratios not in this format will be ignored.
         */
        "aspectRatio"?: string;
        /**
          * Determines how content will be resized to fit its container.
         */
        "fit"?: 'contain' | 'cover';
    }
    interface SuxSwitch {
        /**
          * Checked state of the switch
         */
        "checked"?: boolean;
        /**
          * Disabled state of the switch
         */
        "disabled"?: boolean;
        /**
          * Label for the switch
         */
        "label"?: string;
        /**
          * Name of the switch
         */
        "name"?: string;
        /**
          * Fires when the element loses focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * Fires when the value of the input changes
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * Fires when an alteration to the input's value is made
         */
        "onSuxinput"?: (event: CustomEvent<any>) => void;
        /**
          * Value of the switch
         */
        "value"?: string;
    }
    interface SuxTag {
        /**
          * Prefix
         */
        "hasPrefix"?: boolean;
        /**
          * suffix
         */
        "hasSuffix"?: boolean;
        /**
          * Size
         */
        "size"?: TagSize;
        /**
          * State
         */
        "status"?: TagStatus;
        /**
          * Variant
         */
        "variant"?: TagVariant;
    }
    interface SuxTextArea {
        /**
          * disabled input
         */
        "disabled"?: boolean;
        /**
          * Error
         */
        "error"?: boolean;
        /**
          * Error message
         */
        "errorText"?: string;
        /**
          * Help text
         */
        "helpText"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Label position
         */
        "labelPosition"?: 'top' | 'side';
        /**
          * Fired when an element has lost focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * /**     Fired when the value of the input changes
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * Fired when an alteration to the input's value is committed by the user
         */
        "onSuxinput"?: (event: CustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * read only
         */
        "readonly"?: boolean;
        /**
          * Required
         */
        "required"?: boolean;
        /**
          * size of the input
         */
        "size"?: TextAreaSize;
        /**
          * valid icon
         */
        "validIcon"?: boolean;
        /**
          * value of the input
         */
        "value"?: string;
        /**
          * width of the input
         */
        "width"?: string;
    }
    interface SuxTextField {
        /**
          * disabled input
         */
        "disabled"?: boolean;
        /**
          * Error
         */
        "error"?: boolean;
        /**
          * Error message
         */
        "errorText"?: string;
        /**
          * Help text
         */
        "helpText"?: string;
        /**
          * Label text
         */
        "label"?: string;
        /**
          * Label position
         */
        "labelPosition"?: 'top' | 'side';
        /**
          * Fired when an element has lost focus
         */
        "onSuxblur"?: (event: CustomEvent<any>) => void;
        /**
          * /**     Fired when the value of the input changes
         */
        "onSuxchange"?: (event: CustomEvent<any>) => void;
        /**
          * Fired when an alteration to the input's value is committed by the user
         */
        "onSuxinput"?: (event: CustomEvent<any>) => void;
        /**
          * Placeholder text
         */
        "placeholder"?: string;
        /**
          * read only
         */
        "readonly"?: boolean;
        /**
          * Required
         */
        "required"?: boolean;
        /**
          * size of the input
         */
        "size"?: TextFieldSize;
        /**
          * Input type
         */
        "type"?: TextFieldType;
        /**
          * valid icon
         */
        "validIcon"?: boolean;
        /**
          * value of the input
         */
        "value"?: string;
        /**
          * width of the input
         */
        "width"?: string;
    }
    interface IntrinsicElements {
        "sux-actionable": SuxActionable;
        "sux-avatar": SuxAvatar;
        "sux-body": SuxBody;
        "sux-button": SuxButton;
        "sux-checkbox": SuxCheckbox;
        "sux-code": SuxCode;
        "sux-detail": SuxDetail;
        "sux-field-label": SuxFieldLabel;
        "sux-heading": SuxHeading;
        "sux-help-text": SuxHelpText;
        "sux-icon": SuxIcon;
        "sux-icon-button": SuxIconButton;
        "sux-icon-library": SuxIconLibrary;
        "sux-link": SuxLink;
        "sux-menu-item": SuxMenuItem;
        "sux-picker": SuxPicker;
        "sux-radio": SuxRadio;
        "sux-radio-group": SuxRadioGroup;
        "sux-responsive-media": SuxResponsiveMedia;
        "sux-switch": SuxSwitch;
        "sux-tag": SuxTag;
        "sux-text-area": SuxTextArea;
        "sux-text-field": SuxTextField;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sux-actionable": LocalJSX.SuxActionable & JSXBase.HTMLAttributes<HTMLSuxActionableElement>;
            "sux-avatar": LocalJSX.SuxAvatar & JSXBase.HTMLAttributes<HTMLSuxAvatarElement>;
            "sux-body": LocalJSX.SuxBody & JSXBase.HTMLAttributes<HTMLSuxBodyElement>;
            "sux-button": LocalJSX.SuxButton & JSXBase.HTMLAttributes<HTMLSuxButtonElement>;
            "sux-checkbox": LocalJSX.SuxCheckbox & JSXBase.HTMLAttributes<HTMLSuxCheckboxElement>;
            "sux-code": LocalJSX.SuxCode & JSXBase.HTMLAttributes<HTMLSuxCodeElement>;
            "sux-detail": LocalJSX.SuxDetail & JSXBase.HTMLAttributes<HTMLSuxDetailElement>;
            "sux-field-label": LocalJSX.SuxFieldLabel & JSXBase.HTMLAttributes<HTMLSuxFieldLabelElement>;
            "sux-heading": LocalJSX.SuxHeading & JSXBase.HTMLAttributes<HTMLSuxHeadingElement>;
            "sux-help-text": LocalJSX.SuxHelpText & JSXBase.HTMLAttributes<HTMLSuxHelpTextElement>;
            "sux-icon": LocalJSX.SuxIcon & JSXBase.HTMLAttributes<HTMLSuxIconElement>;
            "sux-icon-button": LocalJSX.SuxIconButton & JSXBase.HTMLAttributes<HTMLSuxIconButtonElement>;
            "sux-icon-library": LocalJSX.SuxIconLibrary & JSXBase.HTMLAttributes<HTMLSuxIconLibraryElement>;
            "sux-link": LocalJSX.SuxLink & JSXBase.HTMLAttributes<HTMLSuxLinkElement>;
            "sux-menu-item": LocalJSX.SuxMenuItem & JSXBase.HTMLAttributes<HTMLSuxMenuItemElement>;
            "sux-picker": LocalJSX.SuxPicker & JSXBase.HTMLAttributes<HTMLSuxPickerElement>;
            "sux-radio": LocalJSX.SuxRadio & JSXBase.HTMLAttributes<HTMLSuxRadioElement>;
            "sux-radio-group": LocalJSX.SuxRadioGroup & JSXBase.HTMLAttributes<HTMLSuxRadioGroupElement>;
            "sux-responsive-media": LocalJSX.SuxResponsiveMedia & JSXBase.HTMLAttributes<HTMLSuxResponsiveMediaElement>;
            "sux-switch": LocalJSX.SuxSwitch & JSXBase.HTMLAttributes<HTMLSuxSwitchElement>;
            "sux-tag": LocalJSX.SuxTag & JSXBase.HTMLAttributes<HTMLSuxTagElement>;
            "sux-text-area": LocalJSX.SuxTextArea & JSXBase.HTMLAttributes<HTMLSuxTextAreaElement>;
            "sux-text-field": LocalJSX.SuxTextField & JSXBase.HTMLAttributes<HTMLSuxTextFieldElement>;
        }
    }
}
