
name: Transform Figma Tokens to CSS using Style Dictionary

# Controls when the workflow will run
on: [push, pull_request]

# Jobs
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js Env
        uses: actions/setup-node@v2.4.0
      
      # Install Dependencies
      - run: npm install
      
      # Transform
      - run: npm run build
      
      # Add files that were created.
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: transformed FT to CSS with SD
